# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Philipp Zuber
title: Project Manager Urban Data Plattform
email: philipp.zuber@posteo.de
website: philipp.zuber.space

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  zuberspace
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: philipp-z-104546174
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's <mark>Philipp</mark>. 

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Smart City <br> Projectmanager
        link: https://www.bochum-smartcity.de/ueber-uns
        link_text: bochum-smartcity.de
        additional_links:
          - title:  Bochum.de
            icon: fas fa-building
            url: https://www.bochum.de/Chief-Digital-Officer/OpenData-Ansprechperson
          - title:  Bochum GitHub
            icon: fab fa-github
            url: https://github.com/StadtBochum
          - title:  Bochum GitLab OpenCode
            icon: fab fa-gitlab
            url: https://gitlab.opencode.de/StadtBochum/
        sub_title: Urban data plattform & open data
        caption: July 2023 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Combining my knowledge in nature, data, and IT science, I have taken on the role of Project Manager within the Smart City team at the City of Bochum. Leading a significant initiative, I am driving the establishment of an Urban Data Platform for Bochum, focusing on the effective organization and utilization of open data. This position enables me to apply my scientific expertise and technical skills to contribute to the city's smart initiatives, working towards innovative solutions that enhance urban living in Bochum through strategic data management.
      - layout: left
        title: Data Science Trainee
        link: https://www.neuefische.de/bootcamp/data-science
        link_text: neuefische.com
        additional_links:
          - title:  neueFische GitHub
            icon: fab fa-github
            url: https://github.com/neuefische
        sub_title: Full-time coding bootcamp
        caption: April 2022 - June 2023
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          I completed an intensive 3-month Data Science bootcamp where I immersed myself in Python programming. The curriculum covered a wide array of topics, from fundamental data manipulation and analysis to machine learning algorithms. Throughout the program, I gained hands-on experience in real-world projects, applying statistical and machine learning techniques to solve complex problems. This intensive training not only enhanced my proficiency in Python but also equipped me with valuable skills in data analysis and machine learning, setting a strong foundation for my journey in the field of data science.
          
          <mark>Python</mark> <mark>Machine Learning</mark> <mark>Neural Networks</mark> <mark>Data visualization</mark> <mark>Git</mark> <mark>SQL</mark> <mark>Scrum</mark>
      - layout: left
        title: Full Stack Developer
        link: https://www.hls-database.com
        link_text: hls-database.com
        sub_title: Freelancer
        caption: April 2020 - June 2022
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          As a full-stack developer, I spearheaded the creation of a specialized database for Hydrous Layer Silicates at the university using Django. My role involved designing an efficient database structure, implementing advanced search features, and ensuring data security. This project not only showcased my technical expertise but also contributed significantly to enhancing research capabilities within the academic community.
          
          <mark>Django</mark> <mark>Database design</mark> <mark>PostgreSQL</mark> <mark>Tailwind CSS</mark> <mark>Alpine.js</mark> <mark>Charts.js</mark> <mark>jQuery</mark> <mark>gunicorn</mark>
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left  
        title: PhD Geoscience
        caption: 2018 - Present
        sub_title: Ruhr-University Bochum
        # quote: >
        description:
          I dedicated four years to research as a researcher at the university and commenced my Ph.D. While I have made significant contributions during this time, I have yet to complete my doctoral studies as of today. Despite this, my experience in the research domain has provided me with valuable insights and skills that I continue to leverage in various capacities.
      - layout: left  
        title: MSc Geoscience
        caption: 2015 - 2018
        sub_title: Ruhr-University Bochum
        quote: | # >
          "Crystallography allows us to see the world in a different light, revealing the hidden patterns and structures that underpin our understanding of matter." - Paul F. McMillan
        description: | # this will include new lines to allow paragraphs
          I earned a Master of Science degree in Geosciences, with a focus on crystal chemistry, crystal physics, and experimental crystallography. Additionally, I gained expertise in analytical methods for geosciences, as well as simulation and modeling techniques.

          In my Master thesis I focused on the elastic behavior of crystalline materials, with a particular emphasis on oxides and silicates. Through my research, I refined the elastic S-values of individual oxide components using experimental data, and used these values to calculate the S-values of composite oxides and silicates. The results demonstrated an improved agreement between experimental and calculated S-values. Overall, Master's degree provided me with advanced skills in research methodology, data analysis, and problem-solving that are applicable in various fields of geoscience.
          
          <mark>XRD</mark> <mark>EPMA/WDX</mark> <mark>SEM/EDX</mark> <mark>DTA/TG</mark> <mark>DSC</mark> <mark>RUS</mark> <mark>RFA</mark> <mark>UV/VIS+IR</mark> <mark>AAS</mark> <mark>AFM</mark> <mark>NMR</mark>
      - layout: left
        title: BSc Geoscience
        caption: 2010 - 2014
        sub_title: Ruhr-University Bochum
        quote: >
          "Geology is the study of the past, but it is also the key to our future." - Marcia McNutt
        description: | # this will include new lines to allow paragraphs
          My Bachelor's degree in geosciences provided me with extensive knowledge and practical experience in geology, chemistry, physics, and mathematics. The program included exciting field trips, which allowed me to apply my knowledge in real-world settings and gain valuable hands-on experience. I also completed a Bachelor's thesis that explored the genesis of unusual mineralizations in Ladinian deposits in South Tyrol, providing me with experience in conducting independent research, analyzing data, and presenting findings. Overall, my Bachelor's degree and field trip experiences have equipped me with valuable knowledge and skills in the field of geosciences.

          During my Bachelor's degree, I was actively involved in the student association as a member of the Institute Council and the Quality Assurance committee. I also served as the IT officer, ensuring that students had access to the necessary technological resources for their studies.

          In addition to my administrative roles, I participated in various social activities organized by the student association, such as field trips with first-year students. Being part of the association provided me with valuable opportunities to network with my peers, develop my leadership skills, and contribute to the betterment of the student experience.
  
          <mark>Geology</mark> <mark>Mineralogy</mark> <mark>Crystallography</mark> <mark>Geophysics</mark> <mark>Petrology</mark> <mark>Tectonics</mark> <mark>Sedimentology</mark> <mark>Paleontology</mark> <mark>Geography</mark> <mark>Maths</mark> <mark>Physics</mark> <mark>Chemistry</mark>
  - title: Sabbatical # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Educational trip
        caption: 2014 - 2015
        sub_title: Southeast Asia and New Zealand
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my 10-month trip around Southeast Asia (including Thailand, Laos, Cambodia, Malaysia, the Philippines, Borneo, Indonesia) and New Zealand, I gained valuable experience in budget travel, cultural immersion, and adaptability. I learned to navigate various modes of transportation, communicate with people from different backgrounds and cultures, and overcome challenges through resourcefulness and resilience. As a diver, I also had the opportunity to explore the underwater world in several of these countries and gain a greater appreciation for the environment and the importance of preserving it.
          
          This experience has broadened my perspective and enhanced my problem-solving and interpersonal skills.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I have a deep love for exploring the natural world, whether through **diving**, **hiking**, or conquering **via ferratas**. I also enjoy the simplicity of **camping** and **being in nature**. On the tech side, I enjoy tinkering with **mechanical keyboards**, **building DIY drones** and **electronics**, and experimenting with **smart home** technology. When I need a break from the digital world, I like to unwind by playing **video games** or reading a **good book**, and I also find joy in **cooking** and trying out new recipes.

#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
